# Docker H2 configuration
spring.datasource.url=jdbc:h2:tcp://localhost:1521/./volumes/h2/filmorate;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# SQL initialization
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true

# H2 Console (optional)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console